.gitmodules
microservices/netinfra_utils/devices/device_data.csv
microservices/netinfra_utils/devices/device_import.postman_collection.json
startup.sh

Signed-off-by: Jozef Rózsa <jrozsa@frinx.io>

Add import of sample devices

---

microservices/netinfra_utils/workers/netconf_worker.py

Signed-off-by: Adam Chmara <achmara@frinx.io>

Check netconf connected worker fix

---

microservices/netinfra_utils/workers/main.py

Disable deprecated workers

---

microservices/netinfra_utils/workers/standalone_main.py

Enable basic auth for standalone main

---

microservices/netinfra_utils/workers/bi_model.py
microservices/netinfra_utils/workers/bi_service_worker.py
microservices/netinfra_utils/workers/common_worker.py
microservices/netinfra_utils/workers/main.py
microservices/netinfra_utils/workers/uniconfig_worker.py
microservices/netinfra_utils/workers/vll_model.py
microservices/netinfra_utils/workers/vll_service_worker.py
microservices/netinfra_utils/workers/vpls_model.py
microservices/netinfra_utils/workers/vpls_service_worker.py
microservices/netinfra_utils/workers/vpls_test.py
microservices/netinfra_utils/workers/vpls_worker.py

Signed-off-by: Filip Glemba <fglemba@frinx.io>

vpls worker

---

microservices/netinfra_utils/workers/vll_model.py

there was duplicate of set_attributes method, possible result of my merge

remove duplicate of set_attributes method

---

microservices/netinfra_utils/workers/inventory_worker.py

fix get_all_devices_as_tasks in inventory

---

microservices/netinfra_utils/postman.json
microservices/netinfra_utils/workers/uniconfig_worker.py

Crated Checked commit and uniconfig worker refactoring

---

microservices/netinfra_utils/postman.json
microservices/netinfra_utils/workers/inventory_worker.py

Fix bug with unnecessary spaces and Wf param renaming

---

microservices/netinfra_utils/postman.json

Changed input description for Add field to device workflow

---

microservices/netinfra_utils/workers/bi_service_worker.py
microservices/netinfra_utils/workers/common_worker.py
microservices/netinfra_utils/workers/standalone_main.py
microservices/netinfra_utils/workers/vll_service_worker.py
microservices/netinfra_utils/workers/vll_worker.py
microservices/netinfra_utils/workers/vpls_worker.py

Signed-off-by: Filip Glemba <fglemba@frinx.io>

Unification of RPC output and new RPC url

---

microservices/netinfra_utils/workers/inventory_worker.py

Fix Inventory worker for storing field with dash

---

microservices/netinfra_utils/workers/main.py
microservices/netinfra_utils/workers/netconf_worker.py
microservices/netinfra_utils/workflows/Add_netconf_device_to_inventory.json
microservices/netinfra_utils/workflows/Mount_from_inventory.json
microservices/netinfra_utils/workflows/Mount_netconf_device.json
microservices/netinfra_utils/workflows/UNICONFIG_create_snapshot.json
microservices/netinfra_utils/workflows/UNICONFIG_delete_snapshot.json
microservices/netinfra_utils/workflows/UNICONFIG_replace_config_with_snapshot.json

Separate uniconfig-native in workers and workflows, comment unused workers

---

health_check.sh
install.sh

Fix health_check script and rename odl in install.sh

---

microservices/netinfra_utils/devices/device_import.postman_collection.json
microservices/netinfra_utils/workers/uniconfig_worker.py
microservices/netinfra_utils/workflows/Check_uniconfig_node_exists.json
microservices/netinfra_utils/workflows/Create_L2VPN_P2P_OC_uniconfig.json
microservices/netinfra_utils/workflows/Write_data_to_netconf_testool.json
startup.sh

Added workflow for netconf-testtol configuration and adjust L2VPN wf

---

get_uniconfig_logs.sh

Signed-off-by: Jozef Rózsa <jrozsa@frinx.io>

Add script to extract uniconfig logs from docker volume

---

install.sh

Signed-off-by: Jozef Rózsa <jrozsa@frinx.io>

Add dev flag to install script

---

microservices/Dockerfile
microservices/netinfra_utils/workers/cli_worker.py
microservices/netinfra_utils/workers/cli_worker_test.py
microservices/netinfra_utils/workers/frinx_rest.py
microservices/netinfra_utils/workers/inventory_worker.py
microservices/netinfra_utils/workers/netconf_worker.py
microservices/netinfra_utils/workers/netconf_worker_test.py
microservices/netinfra_utils/workers/uniconfig_worker.py
microservices/netinfra_utils/workers/uniconfig_worker_test.py
microservices/netinfra_utils/workers/unified_worker.py
microservices/netinfra_utils/workers/unified_worker_test.py
microservices/netinfra_utils/workflows/Link_aggregation.json

Create test for workers and switch to Python 3.6

---

microservices/Dockerfile
microservices/netinfra_utils/workers/uniconfig_worker_test.py

IssueID: FM-302
Signed-off-by: Ladislav Moravek <lmoravek@frinx.io>

Updated workers to use python3

---

docker-compose.yml

Linked with frinx-uniconfig-ui changes: https://github.com/FRINXio/frinx-uniconfig-ui/pull/92

docker-compose UI build changes

---

startup.sh

Remove Write_data_to_netconf_testool from startup

---

microservices/netinfra_utils/workers/cli_worker.py
microservices/netinfra_utils/workers/frinx_rest.py
microservices/netinfra_utils/workers/netconf_worker.py
microservices/netinfra_utils/workers/uniconfig_worker.py
microservices/netinfra_utils/workers/uniconfig_worker_test.py

Uniconfig transactions

---

microservices/netinfra_utils/workers/cli_worker.py

Fix CLI_get_cli_journal inputKeys

---

microservices/netinfra_utils/workers/uniconfig_worker.py
microservices/netinfra_utils/workers/uniconfig_worker_test.py

Fix uniconfig write for dynamic task

---

README.md
teardown.sh

Added options to remove FM volumes and images

---

install.sh
teardown.sh

into install and teardown to hardcoded docker-cpompose.bridge.yml

Remove symbolic link from install.sh and rewrite general docker-compose

---

microservices/Dockerfile

Added psql library to docker image

---

microservices/netinfra_utils/workers/http_worker.py
microservices/netinfra_utils/workers/main.py

Input and output parameters are identical or similar
to the system HTTP task.
See provided examples.

Add worker based http task

---

microservices/netinfra_utils/workers/netconf_worker.py

Added netconf reconnection stratedy to netconf worker

---

README.md

Signed-off-by: Stanislav Chlebec <schlebec@frinx.io>

fix the way how to restart service for both networking modes

---

microservices/netinfra_utils/workflows/Mount_apply_template_unmount_cli.json

Enable archiving for mount+applytemplate+unount workflow

---

microservices/netinfra_utils/workers/netconf_worker.py

Fix netconf Mount inputKeys

---

show_status.sh

It checks:
- containers status
- IP and PORT
- availability of services
Issue-ID: FM-307
Signed-off-by: Ladislav Moravek <lmoravek@frinx.io>

A healt check script for FM

---

uniconfig/Dockerfile

Signed-off-by: Stanislav Chlebec <schlebec@frinx.io>

Upgrade to UniConfig 4.2.4

---

microservices/netinfra_utils/workers/cli_worker.py
microservices/netinfra_utils/workers/http_worker.py
microservices/netinfra_utils/workers/netconf_worker.py
microservices/netinfra_utils/workers/uniconfig_worker.py

Edit workers description to new format

---

.gitmodules
docker-compose.bridge.yml
docker-compose.host.yml
startup.sh

How to run PR: 
- checkout `frinx-workflow-ui` and `frinx-uniconfig-ui` to `ui-separation` branch
- run `docker-compose -f docker-compose.bridge.yml build uniconfig-ui` to overwrite old uniconfig-ui image
- `./startup.sh -s`
`localhost:5000` is the main UI entry point

API gateway and UI services

---

.gitignore
health_check.sh
install.sh
startup.sh

separation of ui/api and api-gateway created
new containers so deployment needs to be changed accordingly.

fixed deployment from images

---

microservices/netinfra_utils/workers/netconf_worker.py
microservices/netinfra_utils/workers/netconf_worker_test.py

This is similar to UNICONF_read_structured_data, but instead of the uniconf topology it reads from the netconf topology.

Add the Netconf_read_structured_data task

---

generate-workflow-dependency-tree.py

script reads workflows and tasks from conductor
via REST API and analyses dependencies between them.

Added script generating wf-task dependency

---

uniconfig/odl-wrapper.sh

Fixes  issue with passing of token as env variable

Fix passing of token as env

---

composefiles/swarm-uniflow.yml
startup.sh

- set stable versions for all services
- minor fix in startup.sh

Set stable versions for 1.3 release

---

composefiles/swarm-uniflow.yml

Dependent on https://github.com/FRINXio/uniflow-api/pull/3

Add healthcheck for uniflow api

---

composefiles/swarm-uniflow.yml

Dependent on https://github.com/FRINXio/uniflow-micros/pull/9
Check image tag!

Add micros healthcheck

---

composefiles/swarm-uniflow.yml

Bumped micros version to 1.0.4

---

composefiles/swarm-uniflow.yml

Bumped schellar to 1.9.2

---

composefiles/swarm-uniflow-micros.yml
composefiles/swarm-uniflow.yml
startup.sh

Adds switch to start micros optionally

Add switch for micros contaner

---

composefiles/swarm-uniflow-micros.yml
install.sh

- use latest micros
- fixed downloading of micros image during installation

bumped micros to 1.0.5

---

microservices/netinfra_utils/workers/cli_worker.py
microservices/netinfra_utils/workers/cli_worker_test.py

Default value is 'tree-parser'.

Add configurable 'parsing-engine' option.

---

install.sh

Add 'add-apt-repository' dependency

---

composefiles/swarm-uniflow.yml
startup.sh

Refactor install script params parsing

Add http switch

---

composefiles/swarm-uniflow.yml

Dependent on https://github.com/FRINXio/frinx-dashboard/pull/5

Add healthcheck for dashboard

---

composefiles/swarm-uniflow.yml

To be able to attach container for running tests

Make network attachable

---

composefiles/swarm-uniflow.yml
startup.sh

Change config file paths to absolute.

Change docker mount pathes to absolute

---

composefiles/swarm-uniconfig.yml
config/uniconfig/frinx/uniconfig/init_schema.sql

- bumped version
- changed db schema

Update uniconfig to 4.2.6

---

composefiles/swarm-uniflow.yml

Release v1.4.0

---

composefiles/swarm-uniflow-micros.yml
composefiles/swarm-uniflow.yml

Bump versions with mount fix

---

composefiles/swarm-uniflow.yml
config/frinx-frontend/config.json

Change FM-UI to monorepo

---

composefiles/swarm-uniflow.yml

workflow-proxy added to frinx machine instead of uniflow-api

Add workflow-proxy to Frinx Machine

---

composefiles/swarm-uniflow.yml
config/krakend/krakend.json
config/krakend/tls/https/tls.json
startup.sh

http / https switch with krakend

Add tls settings to krakend

---

startup.sh
teardown.sh

Changes for krakend usage,
fix input arguments ordering problem,
add functions for safe docker volume deleting (just frinx machine volumes will be deleted)

Update startup script

---

composefiles/swarm-uniconfig.yml

Enable G1GC and GC logging for uniconfig container

---

config/frinx-frontend/config.json
config/krakend/templates/frinx_frontend.tmpl

/frinxui as based URL for frinx-frontend

---

config/krakend/settings/frinx_frontend_settings.json
config/krakend/templates/frinx_frontend.tmpl

Linked PR: https://github.com/FRINXio/frinx-frontend/pull/57

fix frinx-frontend routing

---

composefiles/swarm-uniflow.yml
config/conductor/config.properties
config/krakend/settings/workflow_proxy_settings.json

- Added variables for new conductor image
- Added proxy for Get Postgres External Storage data
Signed-off-by: vklevlanyk <vklevlanyk@frinx.io>

FM-729 Implement PSQL based object storage for Conductor

---

config/conductor/config.properties

Signed-off-by: vklevlanyk <vklevlanyk@frinx.io>

Fixed some comments

---

composefiles/swarm-uniflow.yml
config/krakend/krakend.json
config/krakend/settings/workflow_proxy_docs_settings.json
config/krakend/templates/workflow_proxy_docs.tmpl
config/workflow-proxy/uniflow.json

OpenAPI documentation for Uniflow and KrakenD endpoint for workflow-proxy swagger-ui

KrakenD endpoints for workflow-proxy swagger-ui

---

composefiles/swarm-uniconfig.yml
config/uniconfig/frinx/uniconfig/config/lighty-uniconfig-config.json
config/uniconfig/frinx/uniconfig/config/logback.xml
config/uniconfig/run_uniconfig.sh

Unique log file for each uniconfig instance

Separate logging files for multiinstance Uniconfig-controller

---

CHANGELOG.md
README.md
composefiles/swarm-uniflow.yml

Change documentation and docker tags for services

Frinx Machine 1.8 RELEASE

---

composefiles/swarm-uniconfig.yml
config/uniconfig/frinx/uniconfig/config/lighty-uniconfig-config.json
config/uniconfig/frinx/uniconfig/config/logback.xml

Uniconfig version 4.2.10-rc11 compatible with device inventory (without authorization header)

Bump Uniconfig version

---

azure_ad.sh
composefiles/swarm-uniconfig.yml
config/frinx-frontend/config_template.json
config/krakend/scripts/wp_azure_swagger.lua
config/krakend/settings/workflow_proxy_docs_settings.json
config/krakend/templates/workflow_proxy_docs.tmpl
config/uniconfig/frinx/uniconfig/config/lighty-uniconfig-config.json
config/uniconfig/frinx/uniconfig/config/logback.xml

- print help output to azure_ad with -h
- update uniconfig image and config files
- krakend uniconfig swagger ui
- modify swagger ui on the fly

Frinx Machine minor release updates

---

README.md
config/uniconfig/frinx/uniconfig/config/lighty-uniconfig-config.json
docs/azure_ad.md

minimize problem with expired transaction id in device inventory UI

Increase uniconfig transaction age and timeout

---

composefiles/support/swarm-monitoring.yml
config/monitoring/grafana/db_cert_monitoring.json
config/monitoring/telegraf/telegraf.conf

-telegraf x509 plugin used for checking validation of certificates
-data stored in influxdb and vizalized by grafana dashboard

Monitoring certificates validation used in Frinx Machine

---

composefiles/support/swarm-monitoring.yml
composefiles/swarm-uniconfig.yml
config/monitoring/grafana/db_uniconfig_monitoring.json
config/monitoring/telegraf/telegraf.conf
config/uniconfig/frinx/uniconfig/config/lighty-uniconfig-config.json
config/uniconfig/frinx/uniconfig/config/logback.xml
config/uniconfig/run_uniconfig.sh
generate_uc_compose.sh

Store uniconfig metrics to InfluxDB database and visualize in Grafana dashboard.

Uniconfig statistic monitoring

---

composefiles/swarm-uniconfig.yml
composefiles/swarm-uniflow.yml
composefiles/swarm-unistore.yml
generate_uc_compose.sh
startup.sh

- ability to deploy Uniconfig zone to multiple VMs
- use constrain placement to select nodes

Traefik in swarm mode

---

composefiles/support/swarm-monitoring.yml
composefiles/swarm-uniconfig.yml
composefiles/swarm-unistore.yml
composefiles/swarm-workflow-manager.yml

- fix problem with persisting old logs from exited container

Disable keep-file for loki plugin

---

composefiles/swarm-uniconfig.yml
composefiles/swarm-workflow-manager.yml
config/krakend/krakend.json
startup.sh

SSH websocket

---

composefiles/swarm-kafka-connector.yml
config/connect/log4j.properties
teardown.sh

- log rotation
- teardown script option to remove kafka services only
- teardown script remove debezium connector slot from postgresql db

Debezium connector configuration improvement

---

composefiles/swarm-kafka-connector.yml
config/connect/register_postgres.sh

Create conductor kafka topic on startup

Add default kafka retention timeout

---

config/krakend/partials/content_header.tmpl
config/krakend/partials/jwt_fake_config.tmpl
config/krakend/partials/uc_modifiers.tmpl
config/krakend/scripts/header_check.lua
config/krakend/templates/uniconfig.tmpl

- add Content-Type only when it doesnt exist
Type: Bugfix
JIRA: DEP-682

Filter header
